### ISSUE TITLE
dev-perl/X + Y + Z TODO Apr 2016

### ISSUE THREAD

**Issue by kentfredric** [kentfredric/gentoo#12]
- [x] XML::Catalog                       1.03  ( Version ambiguous )
- [x] XML::DOM                           1.45 
- [x] XML::DT                            0.68
- [x] XML::Encoding                      2.09
  - [ ] bz check
- [x] XML::Entities                    1.0002
  - [x] bz check
- [x] XML::Feed                          0.53 
- [x] XML::Filter::DOMFilter::LibXML     0.04
- [x] XML::LibXML                      2.0124 
  - [ ] bz check
- [x] XML::LibXML::Simple                0.96
- [x] XML::Parser::Lite                 0.721
- [x] XML::RSS                           1.59
  - [ ] bz check
- [x] XML::XPath                         1.35
  - [x] bz check
- [x] YAML::LibYAML                      0.62
  - [ ] bz check
- [x] pkgmove dev-perl/yaml dev-perl/YAML
- [x] ZMQ::Constants                     1.04 
- [x] ZMQ::LibZMQ2                       1.09

**Comment by kentfredric** [comment]
XML::Encoding:

```
 242172 - NEEDINF RESOLVE : dev-perl/XML-Encoding does not need XML-Parser at build-time, beside for testing
```

**Comment by kentfredric** [comment]
XML::Entities:

```
 340927 - OBSOLET RESOLVE : XML::Entities ebuild
```

**Comment by kentfredric** [comment]
XML::LibXML

```
  48371 - INVALID RESOLVE : QA/Ebuild Violations: dev-perl/XML-LibXML
 190081 - CANTFIX RESOLVE : dev-perl/XML-LibXML-1.62.001-r1 does not emerge (IOError: [Errno 22])
 237360 -   LATER RESOLVE : [QA] dev-perl/XML-LibXML doesn't respect LDFLAGS (patch provided)
 285685 - TEST-RE RESOLVE : dev-perl/XML-LibXML-1.69 fails tests
 422055 - WONTFIX RESOLVE : Please stabilize =dev-perl/XML-LibXML-1.980.0
 514956 - INVALID RESOLVE : dev-perl/XML-LibXML-2.1.400 - !!! Couldn't download 'XML-LibXML-2.0014.tar.gz'. Aborting.
 551740 - INVALID RESOLVE : dev-perl/XML-LibXML-2.12.100 compile fails: Couldn't find C compiler
 567130 -         UNCONFI : dev-perl/XML-LibXML-2.12.100::gentoo installs "nothing"
```

**Comment by kentfredric** [comment]
XML::RSS

```
4 entries in summary
  19305 -   LATER VERIFIE : XML-RSS-1.02.ebuild (New Package)
  22739 - WONTFIX RESOLVE : An ebuild for the XML::RSS perl module
```

**Comment by kentfredric** [comment]
XML::XPath

```
 461650 - INVALID RESOLVE : dev-perl/XML-XPath ebuild request
```

**Comment by kentfredric** [comment]
YAML::LibYAML

```
410653 -         IN_PROG : dev-perl/YAML-LibYAML bundles a copy of LibYAML aka dev-libs/libyaml
```
