### ISSUE TITLE
dev-perl/B TODO Apr 2016

### ISSUE THREAD

**Issue by kentfredric** [kentfredric/gentoo#14]
- [x] BSD::Resource                    1.2909
- [x] Bio::ASN1::EntrezGene              1.70
- [ ] https://metacpan.org/release/LDS/Bio-SamTools-1.43
  - Needs BioPerl 1.6.9.1 .... Been broken for a long time.
- [x] Business::ISBN                    2.010
  - 2.09_02 instead, as its the last working version.
- [x] Business::ISBN::Data           20140910.003
- [x] Business::Tax::VAT::Validation     1.10
