### ISSUE TITLE
dev-perl/C TODO Apr 2016

### ISSUE THREAD

**Issue by kentfredric** [kentfredric/gentoo#15]
- [x] CGI                                4.31
- [x] CGI::Emulate::PSGI  0.22
- [x] CPAN::Checksums                    2.10
- [x] CPAN::Meta::Check 0.013
- [x] CPAN::Mini                     1.111016 
- [x] CPAN::Perl::Releases               2.88 
- [x] Cache                              2.11
- [x] Cache::FastMmap                    1.44
- [x] Canary::Stability                  2011
- [x] Capture::Tiny                      0.42
- [x] Carp::Clan                           6.06
- [x] CDB_File 0.99
- [x] Class::Accessor::Lite              0.08 
- [x] Class::Base                        0.06 
- [x] Class::C3 0.31
- [x] Class::ErrorHandler                0.04 
- [x] Class::Load::XS                    0.09
- [x] Class::Method::Modifiers           2.12
- [x] Class::Std                        0.013
- [x] Class::Tiny                       1.004
- [x] Class::Unload                      0.09
- [x] Class::Virtual                     0.07
- [x] Color::Calc                       1.074
- [x] Config::Any                        0.27
- [x] Config::Grammar  0.11
- [x] Config::IniFiles 2.92
- [x] Contextual::Return             0.004008
- [x] Convert::Binary::C                 0.78
- [x] Convert::Color                     0.11
- [x] Coro                               6.511
- [x] Crypt::OpenPGP                     1.12 
- [x] Crypt::OpenSSL::Bignum             0.06 
- [x] Crypt::OpenSSL::Random             0.11 
- [x] Crypt::RIPEMD160                   0.06
- [x] Crypt::Random::Source              0.12 
- [x] Crypt::SMIME      0.17
- [x] Crypt::URandom                     0.36 
- [x] CryptX                            0.039
- [x] Curses                             1.36
- [x] pkgmove dev-perl/class-loader dev-perl/Class-Loader
- [x] pkgmove dev-perl/convert-ascii-armour dev-perl/Convert-ASCII-Armour
- [x] pkgmove dev-perl/convert-pem dev-perl/Convert-PEM
- [ ] https://metacpan.org/release/CHARTGRP/Chart-2.4.10
