### ISSUE TITLE
dev-perl/M -> dev-perl/P TODO List Feb 2016

### ISSUE THREAD

**Issue by kentfredric** [kentfredric/gentoo#5]
- [ ] Get somebody to bump dev-perl/Mac-Pasteboard
- [x] rename dev-perl/math-pari to dev-perl/Math-Pari
- [ ] purge MooseX::Role::WithOverloading 
  - [ ] Fix MooseX::Role::Parameterized 
- [ ] keep an eye on upstream for `Locale::getext`, package might need renaming, might not.
- [ ] fix `app-misc/note` having garbage deps
- [x] bump `dev-perl/Net-Z3950-ZOOM` (dilfridged)
  
   Presently new version requires `yaz >= 4`, which is hardmasked since 2012, + https://bugs.gentoo.org/show_bug.cgi?id=522674 
- [ ] Try the patch in bug https://bugs.gentoo.org/show_bug.cgi?id=522698 agains't 2.0.8 instead and see if it works, instead of using the SVN-pre-release.
- [ ] Get [Modern Perl](https://github.com/chromatic/Modern-Perl) using [MetaJSON]
- [x] bump https://metacpan.org/release/PDF-Create
- [ ] bump https://metacpan.org/pod/PDL # Actually, CBF with this 
- [x] rename dev-perl/Period -> https://metacpan.org/release/Time-Period
- [x] bump https://metacpan.org/release/Perl-Critic
- [x] bump https://metacpan.org/release/Perl-Critic-Deprecated
- [x] bump https://metacpan.org/release/PerlIO-gzip
- [x] bump https://metacpan.org/release/Perl-Tags
- [x] rename dev-perl/perltidy -> https://metacpan.org/release/Perl-Tidy && bump 
- [x] bump https://metacpan.org/release/Plack
- [x] work out why I bumped dev-perl/Pod-LaTeX in overlay and backport the fix
- [x] bump https://metacpan.org/release/Pod-Readme
- [x] bump https://metacpan.org/release/Pod-Spell
- [x] work out why I have POE in local-portage  ( turned out to be `eix` messing with me )
- [x] bump https://metacpan.org/release/POE-Component-Client-DNS
- [x] bump https://metacpan.org/release/POE-Component-IKC
- [ ] Unfuck my maintainership of PortageXS
- [x] bump https://metacpan.org/release/POSIX-strftime-Compiler
- [x] bump https://metacpan.org/release/PostScript-Simple
- [x] bump https://metacpan.org/release/PPIx-Regexp
- [x] bump https://metacpan.org/release/Probe-Perl
- [x] bump https://metacpan.org/release/Proc-Daemon
- [x] bump https://metacpan.org/release/Proc-ProcessTable
- [x] bump https://metacpan.org/release/Proc-Simple
- [x] bump https://metacpan.org/release/Proc-Wait3
- [x] If you have the time and inclination, wish from robbat2: Mail::DMARC :)
- [ ] Get [Perl::Critic](https://metacpan.org/release/Perl-Critic) using META.json properly instead of folding Test dependencies into frigging build.

**Comment by kentfredric** [comment]
- [ ] Get somebody to bump dev-perl/Mac-Pasteboard

**Comment by kentfredric** [comment]
- [ ] rename dev-perl/math-pari to dev-perl/Math-Pari

**Comment by kentfredric** [comment]
- [ ] purge MooseX::Role::WithOverloading

**Comment by kentfredric** [comment]
- [ ] keep an eye on upstream for `Locale::getext`, package might need renaming, might not.

**Comment by kentfredric** [comment]
- [ ] fix `app-misc/note` having garbage deps

**Comment by kentfredric** [comment]
- [ ] bump `dev-perl/Net-Z3950-ZOOM`

Presently new version requires `yaz >= 4`, which is hardmasked since 2012, + https://bugs.gentoo.org/show_bug.cgi?id=522674

**Comment by kentfredric** [comment]
- [ ] Try the patch in bug https://bugs.gentoo.org/show_bug.cgi?id=522698 agains't 2.0.8 instead and see if it works, instead of using the SVN-pre-release.

**Comment by kentfredric** [comment]
- [ ] Get [Modern Perl](https://github.com/chromatic/Modern-Perl) using [MetaJSON]

**Comment by kentfredric** [comment]
- [ ] bump https://metacpan.org/release/PDF-Create
- [ ] bump https://metacpan.org/pod/PDL # Actually, CBF with this 
- [ ] rename dev-perl/Period -> https://metacpan.org/release/Time-Period
- [ ] bump https://metacpan.org/release/Perl-Critic
- [ ] bump https://metacpan.org/release/Perl-Critic-Deprecated
- [ ] bump https://metacpan.org/release/PerlIO-gzip
- [ ] bump https://metacpan.org/release/Perl-Tags
- [ ] rename dev-perl/perltidy -> https://metacpan.org/release/Perl-Tidy && bump 
- [ ] bump https://metacpan.org/release/Plack
- [ ] work out why I bumped dev-perl/Pod-LaTeX in overlay and backport the fix
- [ ] bump https://metacpan.org/release/Pod-Readme
- [ ] bump https://metacpan.org/release/Pod-Spell
- [ ] work out why I have POE in local-portage
- [ ] bump https://metacpan.org/release/POE-Component-Client-DNS
- [ ] bump https://metacpan.org/release/POE-Component-IKC
- [ ] Unfuck my maintainership of PortageXS
- [ ] bump https://metacpan.org/release/POSIX-strftime-Compiler
- [ ] bump https://metacpan.org/release/PostScript-Simple
- [ ] bump https://metacpan.org/release/PPIx-Regexp
- [ ] bump https://metacpan.org/release/Probe-Perl
- [ ] bump https://metacpan.org/release/Proc-Daemon
- [ ] bump https://metacpan.org/release/Proc-ProcessTable
- [ ] bump https://metacpan.org/release/Proc-Simple
- [ ] bump https://metacpan.org/release/Proc-Wait3

**Comment by akhuettel** [comment]
- [x] If you have the time and inclination, wish from robbat2: Mail::DMARC :)

**Comment by kentfredric** [comment]
- [ ] Get [Perl::Critic](https://metacpan.org/release/Perl-Critic) using META.json properly instead of folding Test dependencies into frigging build.
