### ISSUE TITLE
dev-perl/T TODO list Apr 2016

### ISSUE THREAD

**Issue by kentfredric** [kentfredric/gentoo#8]
- [x] Term::ReadLine::Gnu                1.31
- [x] Term::Screen                       1.05 
- [x] Term::Shell                        0.09
  - 0.08: Skipped because of license inconsistency
  - 0.07: Skipped because 0.07 has too many regressions: 
    - https://rt.cpan.org/Ticket/Display.html?id=113731
    - https://rt.cpan.org/Ticket/Display.html?id=113730
- [ ] pkgmove dev-perl/TermReadKey -> dev-perl/Term::ReadKey
  - Skipped because upstream hasn't done this, though they will be forced to.
- [x] Test::CPAN::Meta                   0.25
- [x] Test::Command                      0.11
- [x] Test::Deep                        1.120
- [x] Test::Exception                    0.43
- [x] Test::Fatal                       0.014
- [x] Test::Inter                        1.06 
- [x] Test::Memory::Cycle                1.06 
- [x] Test::Mock::LWP::Dispatch          0.08
- [x] Test::MockModule                   0.11
- [x] Test::Perl::Critic                 1.03
- [x] Test::Pod::Coverage                1.10
- [x] Test::Requires                     0.10
- [x] Test::Script                       1.1
- [x] Test::SharedFork                   0.35
- [x] Test::TCP                          2.15 
- [x] Test::Warnings                    0.026
- [x] Test::YAML                         1.06
- [x] Text::Aligner                      0.13
- [x] Text::Autoformat                   1.74 
- [x] Text::CSV_XS                       1.23
- [x] Text::Diff                         1.44 
- [x] Text::FindIndent                   0.11
- [x] Text::Levenshtein                  0.13
- [x] Text::Quoted                       2.09
- [x] Throwable                      0.200013
- [x] Tie::Cycle                        1.221 
- [x] Tie::LLHash                       1.004
- [x] Tie::Simple                        1.04
- [x] Time::Duration                     1.20 
- [x] Time::Duration::Parse              0.13
- [x] pkgmove dev-perl/Time-modules -> Time-ParseDate
- [x] && Time::ParseDate                2015.103
- [x] Tk::JPEG::Lite                    2.015 
- [x] Tree::Simple                       1.26
- [x] Try::Tiny                          0.24
- [x] pkgmove dev-perl/text-template dev-perl/Text-Template
- [x] pkgmove dev-perl/text-wrapper dev-perl/Text-Wrapper
- [x] && Text::Wrapper                      1.05
- [x] pkgmove dev-perl/tie-encryptedhash dev-perl/Tie-EncryptedHash
